/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMODELPDF
#define ROOMODELPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooModelPdf : public RooAbsPdf {
public:
  RooModelPdf() {} ; 
  RooModelPdf(const char *name, const char *title,
	      RooAbsReal& _theta,
	      RooAbsReal& _phi,
	      RooAbsReal& _thetastar,
	      RooAbsReal& _phistar,
	      RooAbsReal& _mt,
	      RooAbsReal& _mW,
	      RooAbsReal& _q,
	      RooAbsReal& _px,
	      RooAbsReal& _py,
	      RooAbsReal& _pz,
	      RooAbsReal& _lambda);
  RooModelPdf(const RooModelPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooModelPdf(*this,newname); }
  inline virtual ~RooModelPdf() { }

protected:

  RooRealProxy theta ;
  RooRealProxy phi ;
  RooRealProxy thetastar ;
  RooRealProxy phistar ;
  RooRealProxy mt ;
  RooRealProxy mW ;
  RooRealProxy q ;
  RooRealProxy px ;
  RooRealProxy py ;
  RooRealProxy pz ;
  RooRealProxy lambda ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooModelPdf,1) // Your description goes here...
};
 
#endif
